# 02 — METR-LA data quality and handoff

The real METR-LA file has been supplied and copied unchanged into `data/raw/metr-la.h5`; `load_context` verifies its recorded checksum before analysis. Executing these cells computes findings from that artifact. The notebook metadata records the actual interpreter, package versions and execution method. Report and metadata outputs can be regenerated from the same raw file.

Person A preserves the canonical raw file byte-for-byte. This notebook audits structure, missing and zero values, candidate outages, constant sensors and abrupt changes. It does not impute, fit forecasting transforms, remove sensors or construct Person B's features.

In [1]:
from pathlib import Path
import os
import sys
os.environ["MPLBACKEND"] = "Agg"
import matplotlib
matplotlib.use("Agg", force=True)

candidates = [Path.cwd(), *Path.cwd().parents]
ROOT = next(
    (candidate for candidate in candidates
     if (candidate / "src/data/run_person_a.py").is_file()
     and (candidate / "configs/data_quality.yaml").is_file()),
    None,
)
if ROOT is None:
    raise RuntimeError("Open this notebook from the project root or its notebooks directory.")
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".mplconfig"))

import numpy as np
import pandas as pd
from IPython.display import Image, JSON, Markdown, display
from src.data.run_person_a import load_context, write_analysis_outputs
from src.data.quality import DEFAULT_CONFIG, analyze_frame

print("Project root:", ROOT)

Project root: /Users/pankajbaid/projects/AML/traffic-flow-capstone

In [2]:
# Verifies all recorded raw-file checksums, reads one HDF5 table and loads
# trusted copied graph metadata. Missing speed data is an explicit error.
context = load_context(ROOT)
df = context["df"]
quality_config = {
    key: value for key, value in context["config"].items()
    if key in DEFAULT_CONFIG
}
analysis = analyze_frame(
    df=df,
    locations=context["locations"],
    graph_sensor_ids=context["graph_sensor_ids"],
    adjacency=context["adjacency"],
    config=quality_config,
)
valid = analysis["valid_speed"]
summary = analysis["summary"]
print("Validation status:", summary["validation_status"])
print("Raw shape:", df.shape)
assert valid.index.equals(df.index) and valid.columns.equals(df.columns)

Validation status: warning
Raw shape: (34272, 207)

## Structural checks and quality summary

Inspect the actual dimensions, start/end, timezone metadata, cadence, duplicates and missing timestamps. The full summary is shown without replacing observed values with nominal benchmark characteristics. Structural failures require resolution before the canonical handoff; warning-level diagnostics are not automatic deletion rules.

In [3]:
display(JSON(summary, expanded=True))
display(pd.DataFrame({"issue": summary["issues"]}))

                                               issue
0  575302 suspect/invalid speed values are masked...
1  135 positive constant runs warrant inspection;...
2  7990 large consecutive speed changes warrant i...

## Sensor identity, locations and missingness

The sensor table follows HDF5 column order. Check graph correspondence by sensor ID, not by length alone. Counts named `missing_count` refer to NaN cells; `invalid_count` also includes exact zero, negative and infinite readings. Fractions use existing timestamp rows. Absent timestamps are reported separately below.

In [4]:
display(analysis["sensors"])
display(analysis["missingness_summary"])
display(analysis["missingness_over_time"].head(24))
display(
    analysis["missingness_over_time"].sort_values(
        "invalid_fraction", ascending=False, kind="stable"
    ).head(24)
)

    sensor_id  position  ...  latitude  longitude
0      773869         0  ...  34.15497 -118.31829
1      767541         1  ...  34.11621 -118.23799
2      767542         2  ...  34.11641 -118.23819
3      717447         3  ...  34.07248 -118.26772
4      717446         4  ...  34.07142 -118.26572
..        ...       ...  ...       ...        ...
202    717592       202  ...  34.14604 -118.22430
203    717595       203  ...  34.14163 -118.18290
204    772168       204  ...  34.16542 -118.47985
205    718141       205  ...  34.15133 -118.37456
206    769373       206  ...  34.10262 -118.31747

[207 rows x 28 columns]

    sensor_id  position  ...  negative_fraction  invalid_fraction
0      773869         0  ...                0.0          0.112132
1      767541         1  ...                0.0          0.062704
2      767542         2  ...                0.0          0.062704
3      717447         3  ...                0.0          0.063434
4      717446         4  ...                0.0          0.071866
..        ...       ...  ...                ...               ...
202    717592       202  ...                0.0          0.090365
203    717595       203  ...                0.0          0.066060
204    772168       204  ...                0.0          0.062733
205    718141       205  ...                0.0          0.073704
206    769373       206  ...                0.0          0.063317

[207 rows x 16 columns]

                     missing_count  zero_count  ...  all_zero  all_invalid
2012-03-01 00:00:00              0           2  ...     False        False
2012-03-01 00:05:00              0           2  ...     False        False
2012-03-01 00:10:00              0           2  ...     False        False
2012-03-01 00:15:00              0         207  ...      True         True
2012-03-01 00:20:00              0         207  ...      True         True
2012-03-01 00:25:00              0           2  ...     False        False
2012-03-01 00:30:00              0           2  ...     False        False
2012-03-01 00:35:00              0           2  ...     False        False
2012-03-01 00:40:00              0           2  ...     False        False
2012-03-01 00:45:00              0           2  ...     False        False
2012-03-01 00:50:00              0           2  ...     False        False
2012-03-01 00:55:00              0           2  ...     False        False
2012-03-01 01:00:00              0           2  ...     False        False
2012-03-01 01:05:00              0           2  ...     False        False
2012-03-01 01:10:00              0           2  ...     False        False
2012-03-01 01:15:00              0           1  ...     False        False
2012-03-01 01:20:00              0           1  ...     False        False
2012-03-01 01:25:00              0           1  ...     False        False
2012-03-01 01:30:00              0           1  ...     False        False
2012-03-01 01:35:00              0           2  ...     False        False
2012-03-01 01:40:00              0           3  ...     False        False
2012-03-01 01:45:00              0           3  ...     False        False
2012-03-01 01:50:00              0           3  ...     False        False
2012-03-01 01:55:00              0           3  ...     False        False

[24 rows x 9 columns]

                     missing_count  zero_count  ...  all_zero  all_invalid
2012-03-01 00:15:00              0         207  ...      True         True
2012-03-01 00:20:00              0         207  ...      True         True
2012-03-03 00:15:00              0         207  ...      True         True
2012-03-05 13:30:00              0         207  ...      True         True
2012-03-05 13:35:00              0         207  ...      True         True
2012-03-05 13:40:00              0         207  ...      True         True
2012-03-05 13:45:00              0         207  ...      True         True
2012-03-05 13:50:00              0         207  ...      True         True
2012-03-05 13:55:00              0         207  ...      True         True
2012-03-05 14:00:00              0         207  ...      True         True
2012-03-05 14:05:00              0         207  ...      True         True
2012-03-05 14:10:00              0         207  ...      True         True
2012-03-05 14:15:00              0         207  ...      True         True
2012-03-05 14:20:00              0         207  ...      True         True
2012-03-05 14:25:00              0         207  ...      True         True
2012-03-05 14:30:00              0         207  ...      True         True
2012-03-05 14:35:00              0         207  ...      True         True
2012-03-05 14:40:00              0         207  ...      True         True
2012-03-05 14:45:00              0         207  ...      True         True
2012-03-05 14:50:00              0         207  ...      True         True
2012-03-06 11:55:00              0         207  ...      True         True
2012-03-06 12:00:00              0         207  ...      True         True
2012-03-06 14:10:00              0         207  ...      True         True
2012-03-06 14:15:00              0         207  ...      True         True

[24 rows x 9 columns]

## Missing timestamps and invalid sensor readings

Do not treat adjacent observed rows as five minutes apart across a gap. Person B must create the complete 5-minute grid with missing-row flags before lag and horizon construction. Duplicate or off-grid timestamps must be resolved explicitly. No rows are silently added, removed or averaged in this analysis view.

In [5]:
display(analysis["timestamp_gaps"])
timestamp_details = summary["timestamp_validation"]
display(pd.DataFrame({"missing_timestamp": timestamp_details["missing_timestamps"]}))
display(pd.DataFrame({"off_grid_timestamp": timestamp_details["off_grid_timestamps"]}))
display(pd.Series(summary["value_counts"], name="measured_cells").to_frame())

Empty DataFrame
Columns: [previous_timestamp, next_timestamp, elapsed_minutes, expected_missing_slots, aligned_to_cadence]
Index: []

Empty DataFrame
Columns: [missing_timestamp]
Index: []

Empty DataFrame
Columns: [off_grid_timestamp]
Index: []

                       measured_cells
missing_nan                         0
infinite                            0
zero                           575302
negative_finite                     0
valid_positive_finite         6519002
invalid_total                  575302

## Investigate zeros without assigning an unsupported cause

The [official historical-average baseline](https://github.com/liyaguang/DCRNN/blob/602afd9d767d3aa1c9b3eac51710d6aeee12c227/scripts/eval_baseline_methods.py#L12-L30) excludes zero readings from its means, and [baseline evaluation](https://github.com/liyaguang/DCRNN/blob/602afd9d767d3aa1c9b3eac51710d6aeee12c227/scripts/eval_baseline_methods.py#L89-L106) masks zero targets. The [metric implementation](https://github.com/liyaguang/DCRNN/blob/602afd9d767d3aa1c9b3eac51710d6aeee12c227/lib/metrics.py#L62-L98) applies the supplied null mask.

Our predeclared rule treats exact zeros as benchmark missing/suspect, retains positive near-zero observations and preserves raw bytes. Long zero runs or simultaneous zero readings support investigation; they do not establish whether a particular zero was an outage, corruption or real stopped traffic. Run lengths break at gaps and duplicated timestamps. Duration counts occupied sampling slots; first-to-last timestamp span is one interval shorter.

In [6]:
display(JSON(summary["zero_evidence"], expanded=True))
zero_runs = analysis["zero_runs"]
display(zero_runs.head(50))
display(
    zero_runs.loc[zero_runs["possible_outage"]].sort_values(
        "length", ascending=False, kind="stable"
    ).head(50)
)

   sensor_id  position  ... duration_minutes possible_outage
0     773869         0  ...             10.0           False
1     773869         0  ...              5.0           False
2     773869         0  ...              5.0           False
3     773869         0  ...             25.0           False
4     773869         0  ...             10.0           False
5     773869         0  ...             15.0           False
6     773869         0  ...              5.0           False
7     773869         0  ...              5.0           False
8     773869         0  ...             85.0            True
9     773869         0  ...             35.0           False
10    773869         0  ...             10.0           False
11    773869         0  ...             10.0           False
12    773869         0  ...             10.0           False
13    773869         0  ...             10.0           False
14    773869         0  ...             10.0           False
15    773869         0  ...             10.0           False
16    773869         0  ...             10.0           False
17    773869         0  ...             10.0           False
18    773869         0  ...             15.0           False
19    773869         0  ...             10.0           False
20    773869         0  ...             10.0           False
21    773869         0  ...             10.0           False
22    773869         0  ...             10.0           False
23    773869         0  ...            535.0            True
24    773869         0  ...             15.0           False
25    773869         0  ...             10.0           False
26    773869         0  ...             65.0            True
27    773869         0  ...             60.0            True
28    773869         0  ...             25.0           False
29    773869         0  ...              5.0           False
30    773869         0  ...             10.0           False
31    773869         0  ...              5.0           False
32    773869         0  ...             90.0            True
33    773869         0  ...             25.0           False
34    773869         0  ...            250.0            True
35    773869         0  ...              5.0           False
36    773869         0  ...              5.0           False
37    773869         0  ...             40.0           False
38    773869         0  ...             45.0           False
39    773869         0  ...            100.0            True
40    773869         0  ...             10.0           False
41    773869         0  ...              5.0           False
42    773869         0  ...              5.0           False
43    773869         0  ...           1905.0            True
44    773869         0  ...              5.0           False
45    773869         0  ...              5.0           False
46    773869         0  ...              5.0           False
47    773869         0  ...             95.0            True
48    773869         0  ...              5.0           False
49    773869         0  ...             35.0           False

[50 rows x 7 columns]

      sensor_id  position  ... duration_minutes possible_outage
9291     717490        70  ...           8415.0            True
9393     717491        71  ...           8415.0            True
7921     769444        60  ...           6650.0            True
8407     769443        63  ...           6650.0            True
10516    769431        81  ...           6650.0            True
10636    769430        82  ...           6650.0            True
24462    759772       194  ...           5800.0            True
3281     717804        26  ...           5670.0            True
14537    716968       112  ...           5670.0            True
18053    718496       140  ...           5670.0            True
25123    774204       199  ...           5670.0            True
112      773869         0  ...           5590.0            True
5006     718204        37  ...           5590.0            True
14904    717576       114  ...           5590.0            True
4718     760987        36  ...           5070.0            True
22165    716939       174  ...           4525.0            True
13441    718076       105  ...           4375.0            True
5111     718045        38  ...           4285.0            True
6518     760650        48  ...           4285.0            True
7407     716955        56  ...           4285.0            True
17333    716953       133  ...           4285.0            True
7076     716554        53  ...           4270.0            True
21532    717583       168  ...           4270.0            True
21630    717580       169  ...           4270.0            True
21839    717587       171  ...           4270.0            True
22056    717585       173  ...           4270.0            True
14368    717099       110  ...           4260.0            True
25382    717590       201  ...           4260.0            True
25490    717592       202  ...           4260.0            True
4978     718204        37  ...           4245.0            True
14875    717576       114  ...           4245.0            True
4758     760987        36  ...           4055.0            True
22163    716939       174  ...           3915.0            True
14286    761599       109  ...           2940.0            True
5832     773927        42  ...           2890.0            True
19353    763995       149  ...           2875.0            True
16806    759591       129  ...           2820.0            True
22125    716939       174  ...           2730.0            True
7449     716955        56  ...           2710.0            True
10621    769430        82  ...           2685.0            True
22168    716939       174  ...           2390.0            True
4268     769388        32  ...           2360.0            True
6040     774012        44  ...           2210.0            True
6136     774011        45  ...           2210.0            True
19714    773996       152  ...           2210.0            True
19811    773995       153  ...           2210.0            True
13461    718076       105  ...           2180.0            True
2879     769405        22  ...           2110.0            True
5493     769418        39  ...           2110.0            True
14040    767454       108  ...           2065.0            True

[50 rows x 7 columns]

## Constant sensors, low variance, positive flatlines and jumps

Default inspection thresholds are `std < 1` source-speed unit, zero/positive constant runs of at least 12 slots, and absolute changes of at least 30 source-speed units between consecutive valid five-minute readings. The effective settings below come from config. A flatline or abrupt change may be a real traffic pattern. Full-period flags are descriptive and never authorize sensor removal using held-out data.

In [7]:
display(pd.Series(summary["policy"], name="effective_rule").to_frame())
sensors = analysis["sensors"]
flagged = sensors[
    sensors["is_constant"] | sensors["is_raw_constant"]
    | sensors["is_low_variance"] | (sensors["valid_count"] == 0)
]
display(flagged)
display(analysis["flatline_runs"].sort_values("length", ascending=False).head(50))
display(
    analysis["discontinuities"].sort_values(
        "absolute_change", ascending=False, kind="stable"
    ).head(50)
)

                                                   effective_rule
expected_sensors                                              207
frequency                                         0 days 00:05:00
low_variance_std_threshold                                    1.0
zero_run_min_steps                                             12
flatline_min_steps                                             12
discontinuity_threshold                                      30.0
invalid_values              [NaN, infinity, negative, exact zero]
positive_near_zero                                       retained
imputation                                                   none
raw_modified                                                False
valid_std_ddof                                                  1

Empty DataFrame
Columns: [sensor_id, position, observation_count, valid_count, missing_count, infinite_count, nonfinite_count, zero_count, negative_count, invalid_count, valid_fraction, valid_mean, valid_std, valid_min, valid_median, valid_max, is_constant, is_raw_constant, is_all_zero, is_low_variance, zero_run_count, zero_outage_run_count, max_zero_run, flatline_run_count, max_flatline_run, discontinuity_count, latitude, longitude]
Index: []

    sensor_id  position     start_timestamp  ... length  duration_minutes  speed
8      718076       105 2012-03-07 09:25:00  ...     82             410.0   64.0
80     772669       166 2012-04-30 23:40:00  ...     62             310.0   70.0
93     772669       166 2012-05-14 00:30:00  ...     56             280.0   70.0
122    772669       166 2012-06-03 23:50:00  ...     56             280.0   70.0
117    772669       166 2012-05-29 00:40:00  ...     54             270.0   70.0
124    772669       166 2012-06-06 01:00:00  ...     53             265.0   70.0
94     772669       166 2012-05-15 00:50:00  ...     52             260.0   70.0
34     772669       166 2012-03-21 01:10:00  ...     52             260.0   70.0
54     772669       166 2012-04-10 00:50:00  ...     51             255.0   70.0
81     772669       166 2012-05-02 00:35:00  ...     50             250.0   70.0
118    772669       166 2012-05-30 01:10:00  ...     48             240.0   70.0
88     772669       166 2012-05-10 01:05:00  ...     48             240.0   70.0
39     772669       166 2012-03-28 01:30:00  ...     48             240.0   70.0
67     772669       166 2012-04-17 00:45:00  ...     47             235.0   70.0
32     772669       166 2012-03-19 01:10:00  ...     46             230.0   70.0
68     772669       166 2012-04-18 01:15:00  ...     44             220.0   70.0
66     772669       166 2012-04-16 01:15:00  ...     43             215.0   70.0
57     772669       166 2012-04-12 01:10:00  ...     43             215.0   70.0
128    772669       166 2012-06-11 01:10:00  ...     43             215.0   70.0
115    772669       166 2012-05-28 01:30:00  ...     42             210.0   70.0
22     772669       166 2012-03-08 01:35:00  ...     40             200.0   70.0
47     772669       166 2012-04-02 01:10:00  ...     40             200.0   70.0
86     772669       166 2012-05-08 01:25:00  ...     40             200.0   70.0
33     772669       166 2012-03-20 01:35:00  ...     39             195.0   70.0
37     772669       166 2012-03-25 03:40:00  ...     38             190.0   70.0
40     772669       166 2012-03-29 01:35:00  ...     38             190.0   70.0
120    772669       166 2012-06-02 02:10:00  ...     37             185.0   70.0
29     772669       166 2012-03-16 01:50:00  ...     37             185.0   70.0
51     772669       166 2012-04-04 01:15:00  ...     36             180.0   70.0
70     772669       166 2012-04-19 03:15:00  ...     36             180.0   70.0
96     772669       166 2012-05-17 01:50:00  ...     35             175.0   70.0
38     772669       166 2012-03-26 02:10:00  ...     35             175.0   70.0
19     772669       166 2012-03-06 02:30:00  ...     34             170.0   70.0
9      718496       140 2012-03-08 16:00:00  ...     34             170.0   65.0
3      717804        26 2012-03-07 20:10:00  ...     33             165.0   52.0
114    772669       166 2012-05-27 03:10:00  ...     33             165.0   70.0
49     772669       166 2012-04-03 02:30:00  ...     31             155.0   70.0
91     772669       166 2012-05-12 03:25:00  ...     31             155.0   70.0
59     772669       166 2012-04-13 01:35:00  ...     29             145.0   70.0
75     772669       166 2012-04-24 00:55:00  ...     29             145.0   70.0
42     772669       166 2012-03-30 02:25:00  ...     28             140.0   70.0
44     772669       166 2012-03-31 03:10:00  ...     28             140.0   70.0
71     772669       166 2012-04-20 02:45:00  ...     27             135.0   70.0
121    772669       166 2012-06-03 03:35:00  ...     27             135.0   70.0
55     772669       166 2012-04-11 02:40:00  ...     26             130.0   70.0
123    772669       166 2012-06-05 01:45:00  ...     26             130.0   70.0
90     772669       166 2012-05-11 02:50:00  ...     26             130.0   70.0
110    772669       166 2012-05-25 02:40:00  ...     25             125.0   70.0
105    772669       166 2012-05-22 02:10:00  ...     25             125.0   70.0
52     772669       166 2012-04-06 01:15:00  ...     25             125.0   70.0

[50 rows x 7 columns]

     sensor_id  position  ... speed_change absolute_change
7367    771673       196  ...   -69.666667       69.666667
2502    717491        71  ...   -69.111111       69.111111
2360    773880        67  ...   -68.000000       68.000000
4833    718496       140  ...    67.500000       67.500000
6470    716949       170  ...   -67.000000       67.000000
3438    717488       103  ...    66.400000       66.400000
6587    768469       175  ...    66.400000       66.400000
3437    717488       103  ...   -66.222222       66.222222
6548    717585       173  ...    65.888889       65.888889
4762    716958       139  ...   -65.714286       65.714286
5945    717463       162  ...   -65.500000       65.500000
4874    769346       141  ...    65.375000       65.375000
6586    768469       175  ...   -65.222222       65.222222
4305    717472       127  ...   -65.000000       65.000000
3775    717573       115  ...    64.750000       64.750000
2681    718064        78  ...   -64.600000       64.600000
4935    718499       143  ...   -64.400000       64.400000
2041    774067        62  ...   -64.000000       64.000000
4346    717472       127  ...   -63.750000       63.750000
1414    774011        45  ...   -63.736111       63.736111
5402    717468       155  ...   -63.400000       63.400000
5631    717466       159  ...   -63.166667       63.166667
4898    773904       142  ...   -63.000000       63.000000
4934    718499       143  ...    62.750000       62.750000
6488    717587       171  ...   -62.428571       62.428571
1005    760987        36  ...   -62.400000       62.400000
3077    773023        91  ...   -62.321429       62.321429
5892    717460       161  ...   -62.250000       62.250000
616     769405        22  ...   -62.000000       62.000000
3721    717576       114  ...   -62.000000       62.000000
3277    717486        98  ...   -61.500000       61.500000
4948    764853       144  ...    61.375000       61.375000
4349    717472       127  ...   -61.200000       61.200000
3499    767454       108  ...   -61.166667       61.166667
7291    717456       195  ...   -61.000000       61.000000
1270    772140        41  ...   -60.750000       60.750000
4260    717472       127  ...    60.571429       60.571429
5178    763995       149  ...    60.555556       60.555556
501     771667        16  ...   -60.333333       60.333333
4407    717472       127  ...   -60.333333       60.333333
6242    769345       164  ...    60.125000       60.125000
4258    717472       127  ...   -60.000000       60.000000
5655    717466       159  ...   -60.000000       60.000000
6012    717462       163  ...   -59.875000       59.875000
4590    762329       132  ...   -59.833333       59.833333
5043    717502       146  ...    59.750000       59.750000
1866    773939        61  ...   -59.347222       59.347222
1603    773954        58  ...   -59.333333       59.333333
7292    717456       195  ...    59.166667       59.166667
4042    767523       123  ...   -58.902778       58.902778

[50 rows x 8 columns]

## Inspect raw context around representative zero runs

The first three longest flagged zero runs are selected deterministically for inspection. Their surrounding raw observations and quality-masked views help distinguish isolated zeros from sustained missing sequences. This is descriptive evidence, not a fault classifier. No example is created if no run exists.

In [8]:
longest_runs = zero_runs.sort_values("length", ascending=False, kind="stable").head(3)
for event in longest_runs.itertuples(index=False):
    position = int(event.position)
    start = pd.Timestamp(event.start_timestamp)
    end = pd.Timestamp(event.end_timestamp)
    nearby = (df.index >= start - pd.Timedelta(minutes=15)) & (
        df.index <= end + pd.Timedelta(minutes=15)
    )
    # Bound notebook output while retaining both ends of a long event.
    event_view = pd.DataFrame({
        "raw_speed": df.iloc[:, position].loc[nearby],
        "valid_speed": valid.iloc[:, position].loc[nearby],
    })
    display(Markdown(f"### Sensor {event.sensor_id}: {start} to {end}"))
    if len(event_view) > 40:
        display(event_view.head(20))
        display(Markdown("Middle rows omitted from display; complete event is recorded in metadata."))
        display(event_view.tail(20))
    else:
        display(event_view)
if longest_runs.empty:
    display(Markdown("No exact-zero runs detected in the acquired data."))

### Sensor 717490: 2012-06-05 12:25:00 to 2012-06-11 08:35:00

                     raw_speed  valid_speed
2012-06-05 12:10:00  64.375000    64.375000
2012-06-05 12:15:00  62.777778    62.777778
2012-06-05 12:20:00  61.666667    61.666667
2012-06-05 12:25:00   0.000000          NaN
2012-06-05 12:30:00   0.000000          NaN
2012-06-05 12:35:00   0.000000          NaN
2012-06-05 12:40:00   0.000000          NaN
2012-06-05 12:45:00   0.000000          NaN
2012-06-05 12:50:00   0.000000          NaN
2012-06-05 12:55:00   0.000000          NaN
2012-06-05 13:00:00   0.000000          NaN
2012-06-05 13:05:00   0.000000          NaN
2012-06-05 13:10:00   0.000000          NaN
2012-06-05 13:15:00   0.000000          NaN
2012-06-05 13:20:00   0.000000          NaN
2012-06-05 13:25:00   0.000000          NaN
2012-06-05 13:30:00   0.000000          NaN
2012-06-05 13:35:00   0.000000          NaN
2012-06-05 13:40:00   0.000000          NaN
2012-06-05 13:45:00   0.000000          NaN

Middle rows omitted from display; complete event is recorded in metadata.

                     raw_speed  valid_speed
2012-06-11 07:15:00   0.000000          NaN
2012-06-11 07:20:00   0.000000          NaN
2012-06-11 07:25:00   0.000000          NaN
2012-06-11 07:30:00   0.000000          NaN
2012-06-11 07:35:00   0.000000          NaN
2012-06-11 07:40:00   0.000000          NaN
2012-06-11 07:45:00   0.000000          NaN
2012-06-11 07:50:00   0.000000          NaN
2012-06-11 07:55:00   0.000000          NaN
2012-06-11 08:00:00   0.000000          NaN
2012-06-11 08:05:00   0.000000          NaN
2012-06-11 08:10:00   0.000000          NaN
2012-06-11 08:15:00   0.000000          NaN
2012-06-11 08:20:00   0.000000          NaN
2012-06-11 08:25:00   0.000000          NaN
2012-06-11 08:30:00   0.000000          NaN
2012-06-11 08:35:00   0.000000          NaN
2012-06-11 08:40:00  25.333333    25.333333
2012-06-11 08:45:00  21.375000    21.375000
2012-06-11 08:50:00  17.222222    17.222222

### Sensor 717491: 2012-06-05 12:25:00 to 2012-06-11 08:35:00

                     raw_speed  valid_speed
2012-06-05 12:10:00  61.500000    61.500000
2012-06-05 12:15:00  59.333333    59.333333
2012-06-05 12:20:00  61.000000    61.000000
2012-06-05 12:25:00   0.000000          NaN
2012-06-05 12:30:00   0.000000          NaN
2012-06-05 12:35:00   0.000000          NaN
2012-06-05 12:40:00   0.000000          NaN
2012-06-05 12:45:00   0.000000          NaN
2012-06-05 12:50:00   0.000000          NaN
2012-06-05 12:55:00   0.000000          NaN
2012-06-05 13:00:00   0.000000          NaN
2012-06-05 13:05:00   0.000000          NaN
2012-06-05 13:10:00   0.000000          NaN
2012-06-05 13:15:00   0.000000          NaN
2012-06-05 13:20:00   0.000000          NaN
2012-06-05 13:25:00   0.000000          NaN
2012-06-05 13:30:00   0.000000          NaN
2012-06-05 13:35:00   0.000000          NaN
2012-06-05 13:40:00   0.000000          NaN
2012-06-05 13:45:00   0.000000          NaN

Middle rows omitted from display; complete event is recorded in metadata.

                     raw_speed  valid_speed
2012-06-11 07:15:00   0.000000          NaN
2012-06-11 07:20:00   0.000000          NaN
2012-06-11 07:25:00   0.000000          NaN
2012-06-11 07:30:00   0.000000          NaN
2012-06-11 07:35:00   0.000000          NaN
2012-06-11 07:40:00   0.000000          NaN
2012-06-11 07:45:00   0.000000          NaN
2012-06-11 07:50:00   0.000000          NaN
2012-06-11 07:55:00   0.000000          NaN
2012-06-11 08:00:00   0.000000          NaN
2012-06-11 08:05:00   0.000000          NaN
2012-06-11 08:10:00   0.000000          NaN
2012-06-11 08:15:00   0.000000          NaN
2012-06-11 08:20:00   0.000000          NaN
2012-06-11 08:25:00   0.000000          NaN
2012-06-11 08:30:00   0.000000          NaN
2012-06-11 08:35:00   0.000000          NaN
2012-06-11 08:40:00  65.000000    65.000000
2012-06-11 08:45:00  63.375000    63.375000
2012-06-11 08:50:00  58.555556    58.555556

### Sensor 769444: 2012-06-21 17:35:00 to 2012-06-26 08:20:00

                     raw_speed  valid_speed
2012-06-21 17:20:00   0.000000          NaN
2012-06-21 17:25:00   0.000000          NaN
2012-06-21 17:30:00  29.666667    29.666667
2012-06-21 17:35:00   0.000000          NaN
2012-06-21 17:40:00   0.000000          NaN
2012-06-21 17:45:00   0.000000          NaN
2012-06-21 17:50:00   0.000000          NaN
2012-06-21 17:55:00   0.000000          NaN
2012-06-21 18:00:00   0.000000          NaN
2012-06-21 18:05:00   0.000000          NaN
2012-06-21 18:10:00   0.000000          NaN
2012-06-21 18:15:00   0.000000          NaN
2012-06-21 18:20:00   0.000000          NaN
2012-06-21 18:25:00   0.000000          NaN
2012-06-21 18:30:00   0.000000          NaN
2012-06-21 18:35:00   0.000000          NaN
2012-06-21 18:40:00   0.000000          NaN
2012-06-21 18:45:00   0.000000          NaN
2012-06-21 18:50:00   0.000000          NaN
2012-06-21 18:55:00   0.000000          NaN

Middle rows omitted from display; complete event is recorded in metadata.

                     raw_speed  valid_speed
2012-06-26 07:00:00   0.000000          NaN
2012-06-26 07:05:00   0.000000          NaN
2012-06-26 07:10:00   0.000000          NaN
2012-06-26 07:15:00   0.000000          NaN
2012-06-26 07:20:00   0.000000          NaN
2012-06-26 07:25:00   0.000000          NaN
2012-06-26 07:30:00   0.000000          NaN
2012-06-26 07:35:00   0.000000          NaN
2012-06-26 07:40:00   0.000000          NaN
2012-06-26 07:45:00   0.000000          NaN
2012-06-26 07:50:00   0.000000          NaN
2012-06-26 07:55:00   0.000000          NaN
2012-06-26 08:00:00   0.000000          NaN
2012-06-26 08:05:00   0.000000          NaN
2012-06-26 08:10:00   0.000000          NaN
2012-06-26 08:15:00   0.000000          NaN
2012-06-26 08:20:00   0.000000          NaN
2012-06-26 08:25:00  33.000000    33.000000
2012-06-26 08:30:00  23.222222    23.222222
2012-06-26 08:35:00  22.714286    22.714286

## Persist measured outputs and regenerate the report

`write_analysis_outputs` writes the measured sensor, missingness, gap and diagnostic CSVs and quality summary. It generates the ten descriptive EDA PNGs whenever timestamps are chronological and unique, including to inspect flagged gaps. It writes the timestamp split contract only when structural validation has not failed. The original HDF5 file remains untouched. The report retains any warnings or failures; writing it does not automatically establish successful handoff.

In [9]:
figure_paths = write_analysis_outputs(context, analysis, root=ROOT, plots=True)
print("Report:", ROOT / "reports/data_quality_report.md")
print("Validation status:", summary["validation_status"])
print("EDA figures generated:", len(figure_paths))
report_path = ROOT / "reports/data_quality_report.md"
display(Markdown(report_path.read_text()))

Report: /Users/pankajbaid/projects/AML/traffic-flow-capstone/reports/data_quality_report.md
Validation status: warning
EDA figures generated: 10

# METR-LA data quality report — Person A, Phase 1

**Validation status: WARNING**

## Measured descriptive findings

The source covers **2012-03-01T00:00:00 through 2012-06-27T23:55:00**, with 34,272 timestamps and 207 sensors. Speeds use unverified source units. Calendar groups use the stored clock; no timezone is inferred or converted.

Across **6,519,002 valid positive sensor cells**, mean speed is **58.46**, median **63.22**, and the 5th–95th percentile range is **25.62–68.89**.

Excluded readings total **575,302 / 7,094,304 (8.11%)**; exact zeros account for 575,302. Positive near-zero speeds remain observed. No imputation or trained preprocessing is performed.

Hourly pooled means are lowest at stored hour **17:00 (49.85)** and highest at **22:00 (62.96)**. Daily pooled means are lowest on **Friday (56.32)** and highest on **Sunday (63.21)**.

All temporal means pool valid sensor cells using their counts. They are descriptive associations; unavailable readings may be nonrandom, so these profiles can be biased. Counts and exclusion rates accompany the means.

### Weekday and weekend observations

| day type | Valid cells | Mean speed | Excluded (%) |
| --- | --- | --- | --- |
| Weekday | 4690209 | 57.20 | 7.44 |
| Weekend | 1828793 | 61.68 | 9.78 |

### Traffic-period observations

| period | Valid cells | Mean speed | Excluded (%) |
| --- | --- | --- | --- |
| Weekday morning peak | 574372 | 52.02 | 9.32 |
| Weekday evening peak | 597567 | 48.25 | 5.66 |
| Weekday off-peak | 3518270 | 59.57 | 7.43 |
| Weekend | 1828793 | 61.68 | 9.78 |

Peak windows are weekdays [07:00, 10:00) and [16:00, 19:00); weekday off-peak excludes both windows. Weekend observations are reported separately. Full hourly and day-of-week tables are exported alongside these tables.

### Strongest zero-value evidence

All 207 sensors are zero together in **2,148 timestamp rows (6.27%)**, forming **97** consecutive five-minute blocks. Gaps and duplicate timestamps interrupt blocks.

These simultaneous-zero rows account for **77.2874%** of all exact-zero sensor cells.

The longest simultaneous-zero block has **381 slots**, from **2012-03-26T08:25:00** through **2012-03-27T16:05:00** (1,905 minutes of five-minute slots; the elapsed first-to-last span is one slot shorter).

Sensors with the highest zero rates:

| Sensor | Zero cells | Zero (%) |
| --- | --- | --- |
| 718076 | 6890 | 20.10 |
| 716939 | 6464 | 18.86 |
| 760987 | 5532 | 16.14 |

Longest individual zero runs (slot duration includes all observed five-minute slots):

| sensor_id | position | start_timestamp | end_timestamp | length | duration_minutes | possible_outage |
| --- | --- | --- | --- | --- | --- | --- |
| 717490 | 70 | 2012-06-05 12:25:00 | 2012-06-11 08:35:00 | 1683 | 8,415.00 | True |
| 717491 | 71 | 2012-06-05 12:25:00 | 2012-06-11 08:35:00 | 1683 | 8,415.00 | True |
| 769444 | 60 | 2012-06-21 17:35:00 | 2012-06-26 08:20:00 | 1330 | 6,650.00 | True |

Simultaneous zeros and long zero runs are evidence for investigating unavailable measurements. They do not establish a physical cause or prove an outage. Raw values are preserved, exact zeros are flagged as benchmark missing/suspect, and no sensor is automatically removed.


## Measured dataset validation

All numeric findings below are computed from the checksum-recorded HDF5 file. Source values and timestamp timezone are preserved; speed units are unverified.

### Validation status

```json
"warning"
```

### Issues

```json
[
  "575302 suspect/invalid speed values are masked in valid_speed; raw values are preserved.",
  "135 positive constant runs warrant inspection; readings are retained.",
  "7990 large consecutive speed changes warrant inspection; readings are retained."
]
```

### Dimensions

```json
{
  "timestamps": 34272,
  "unique_timestamps": 34272,
  "sensors": 207,
  "observed_cells": 7094304,
  "expected_timestamps": 34272,
  "expected_grid_cells": 7094304,
  "missing_timestamp_cells": 0
}
```

### Timestamp validation

```json
{
  "start": "2012-03-01T00:00:00",
  "end": "2012-06-27T23:55:00",
  "timezone": null,
  "timezone_note": "Naive source timestamps; no timezone inferred.",
  "expected_sampling_minutes": 5.0,
  "modal_sampling_minutes": 5.0,
  "duplicate_rows": 0,
  "chronologically_ordered": true,
  "missing_timestamp_count": 0,
  "missing_timestamps": [],
  "off_grid_timestamp_count": 0,
  "off_grid_timestamps": [],
  "gap_count": 0
}
```

### Value counts

```json
{
  "missing_nan": 0,
  "infinite": 0,
  "zero": 575302,
  "negative_finite": 0,
  "valid_positive_finite": 6519002,
  "invalid_total": 575302
}
```

### Zero evidence

```json
{
  "all_zero_timestamp_rows": 2148,
  "at_least_90pct_zero_timestamp_rows": 2148,
  "all_invalid_timestamp_rows": 2148,
  "total_zero_runs": 25963,
  "possible_outage_runs": 6942,
  "maximum_zero_run_steps": 1683,
  "interpretation": "Zero is suspect, not proof of an outage or genuinely stopped traffic."
}
```

### Sensor quality

```json
{
  "no_valid_observations": 0,
  "constant_sensors": 0,
  "raw_constant_sensors": 0,
  "all_zero_sensors": 0,
  "low_variance_sensors": 0,
  "positive_flatline_runs": 135,
  "large_discontinuities": 7990
}
```

### Metadata validation

```json
{
  "provided": true,
  "sensor_count": 207,
  "duplicate_sensor_ids": 0,
  "missing_sensor_ids": [],
  "extra_sensor_ids": [],
  "all_sensors_covered": true
}
```

### Graph validation

```json
{
  "sensor_ids_provided": true,
  "adjacency_provided": true,
  "used_as_features": false,
  "sensor_count": 207,
  "duplicate_sensor_ids": 0,
  "same_sensor_set": true,
  "same_sensor_order": true,
  "missing_sensor_ids": [],
  "extra_sensor_ids": [],
  "adjacency_shape": [
    207,
    207
  ],
  "adjacency_shape_valid": true,
  "adjacency_finite": true
}
```

### Policy

```json
{
  "expected_sensors": 207,
  "frequency": "0 days 00:05:00",
  "low_variance_std_threshold": 1.0,
  "zero_run_min_steps": 12,
  "flatline_min_steps": 12,
  "discontinuity_threshold": 30.0,
  "invalid_values": [
    "NaN",
    "infinity",
    "negative",
    "exact zero"
  ],
  "positive_near_zero": "retained",
  "imputation": "none",
  "raw_modified": false,
  "valid_std_ddof": 1
}
```

### Generated at utc

```json
"2026-10-16T16:48:51.671283+00:00"
```

### Speed sha256

```json
"64784b76d6fb8ec9bff4b6decafb354da2bb37840468fdccee5044e511277c05"
```

## Zero and missing-value handling

The [upstream baseline](https://github.com/liyaguang/DCRNN/blob/602afd9d767d3aa1c9b3eac51710d6aeee12c227/scripts/eval_baseline_methods.py#L89-L106) masks zero targets and excludes zero observations from historical averages. We preserve raw bytes, treat exact zero as benchmark missing/suspect, mask NaN/nonfinite/negative values and retain positive near-zero observations. The data alone cannot establish whether any particular zero is stopped traffic, an outage or corruption.

Contiguous zero runs, simultaneous sensor failures, flatlines and large jumps provide diagnostic evidence. Run thresholds are predeclared in config. No sensor is automatically removed, and no full-period statistic is used to fit imputation or model selection. Imputation belongs to Person B and must use only past observations and parameters fitted on training timestamps. Invalid targets must remain masked rather than imputed.

## Diagnostic evidence tables (first 12 rows; full CSVs in metadata)

### Timestamp gaps

None detected.

### Zero runs

| sensor_id | position | start_timestamp | end_timestamp | length | duration_minutes | possible_outage |
| --- | --- | --- | --- | --- | --- | --- |
| 773869 | 0 | 2012-03-01 00:15:00 | 2012-03-01 00:20:00 | 2 | 10.0 | False |
| 773869 | 0 | 2012-03-03 00:15:00 | 2012-03-03 00:15:00 | 1 | 5.0 | False |
| 773869 | 0 | 2012-03-03 10:30:00 | 2012-03-03 10:30:00 | 1 | 5.0 | False |
| 773869 | 0 | 2012-03-03 18:15:00 | 2012-03-03 18:35:00 | 5 | 25.0 | False |
| 773869 | 0 | 2012-03-04 11:05:00 | 2012-03-04 11:10:00 | 2 | 10.0 | False |
| 773869 | 0 | 2012-03-04 18:35:00 | 2012-03-04 18:45:00 | 3 | 15.0 | False |
| 773869 | 0 | 2012-03-04 19:00:00 | 2012-03-04 19:00:00 | 1 | 5.0 | False |
| 773869 | 0 | 2012-03-04 19:10:00 | 2012-03-04 19:10:00 | 1 | 5.0 | False |
| 773869 | 0 | 2012-03-05 13:30:00 | 2012-03-05 14:50:00 | 17 | 85.0 | True |
| 773869 | 0 | 2012-03-05 19:20:00 | 2012-03-05 19:50:00 | 7 | 35.0 | False |
| 773869 | 0 | 2012-03-06 11:55:00 | 2012-03-06 12:00:00 | 2 | 10.0 | False |
| 773869 | 0 | 2012-03-06 14:10:00 | 2012-03-06 14:15:00 | 2 | 10.0 | False |

### Flatline runs

| sensor_id | position | start_timestamp | end_timestamp | length | duration_minutes | speed |
| --- | --- | --- | --- | --- | --- | --- |
| 717804 | 26 | 2012-03-06 12:05:00 | 2012-03-06 14:05:00 | 25 | 125.0 | 46.0 |
| 717804 | 26 | 2012-03-06 14:20:00 | 2012-03-06 15:55:00 | 20 | 100.0 | 46.0 |
| 717804 | 26 | 2012-03-06 16:10:00 | 2012-03-06 17:45:00 | 20 | 100.0 | 46.0 |
| 717804 | 26 | 2012-03-07 20:10:00 | 2012-03-07 22:50:00 | 33 | 165.0 | 52.0 |
| 774067 | 62 | 2012-04-19 02:00:00 | 2012-04-19 03:05:00 | 14 | 70.0 | 70.0 |
| 774067 | 62 | 2012-04-20 02:00:00 | 2012-04-20 03:00:00 | 13 | 65.0 | 70.0 |
| 774067 | 62 | 2012-04-27 02:15:00 | 2012-04-27 03:45:00 | 19 | 95.0 | 70.0 |
| 774067 | 62 | 2012-04-28 03:25:00 | 2012-04-28 04:40:00 | 16 | 80.0 | 70.0 |
| 718076 | 105 | 2012-03-07 09:25:00 | 2012-03-07 16:10:00 | 82 | 410.0 | 64.0 |
| 718496 | 140 | 2012-03-08 16:00:00 | 2012-03-08 18:45:00 | 34 | 170.0 | 65.0 |
| 764853 | 144 | 2012-05-02 17:05:00 | 2012-05-02 18:15:00 | 15 | 75.0 | 70.0 |
| 763995 | 149 | 2012-03-14 02:10:00 | 2012-03-14 03:20:00 | 15 | 75.0 | 70.0 |

### Discontinuities

| sensor_id | position | previous_timestamp | timestamp | previous_speed | speed | speed_change | absolute_change |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 773869 | 0 | 2012-03-01 18:05:00 | 2012-03-01 18:10:00 | 47.111111111111114 | 13.0 | -34.111111111111114 | 34.111111111111114 |
| 773869 | 0 | 2012-03-01 19:35:00 | 2012-03-01 19:40:00 | 30.875 | 66.0 | 35.125 | 35.125 |
| 773869 | 0 | 2012-03-04 10:45:00 | 2012-03-04 10:50:00 | 68.66666666666667 | 25.0 | -43.66666666666667 | 43.66666666666667 |
| 773869 | 0 | 2012-03-04 11:35:00 | 2012-03-04 11:40:00 | 28.0 | 65.0 | 37.0 | 37.0 |
| 773869 | 0 | 2012-03-07 19:30:00 | 2012-03-07 19:35:00 | 24.25 | 62.666666666666664 | 38.416666666666664 | 38.416666666666664 |
| 773869 | 0 | 2012-03-08 15:00:00 | 2012-03-08 15:05:00 | 62.75 | 32.75 | -30.0 | 30.0 |
| 773869 | 0 | 2012-03-09 20:05:00 | 2012-03-09 20:10:00 | 24.125 | 60.22222222222222 | 36.09722222222222 | 36.09722222222222 |
| 773869 | 0 | 2012-03-12 17:45:00 | 2012-03-12 17:50:00 | 60.375 | 27.333333333333332 | -33.04166666666667 | 33.04166666666667 |
| 773869 | 0 | 2012-03-12 18:00:00 | 2012-03-12 18:05:00 | 65.625 | 34.875 | -30.75 | 30.75 |
| 773869 | 0 | 2012-03-12 18:45:00 | 2012-03-12 18:50:00 | 21.5 | 63.888888888888886 | 42.388888888888886 | 42.388888888888886 |
| 773869 | 0 | 2012-03-13 17:10:00 | 2012-03-13 17:15:00 | 64.55555555555556 | 27.0 | -37.55555555555556 | 37.55555555555556 |
| 773869 | 0 | 2012-03-14 15:00:00 | 2012-03-14 15:05:00 | 37.111111111111114 | 5.625 | -31.486111111111114 | 31.486111111111114 |

## EDA figures

Descriptive full-period EDA is not an estimator fitted for forecasting. Missing/suspect speed values are excluded; observed-speed patterns can be biased by nonrandom missingness. Hours use the stored clock; peak definitions are weekdays 07:00–10:00 and 16:00–19:00, half-open intervals.

- [overall speed distribution](../figures/overall_speed_distribution.png)

- [sensor speed distribution](../figures/sensor_speed_distribution.png)

- [average speed by hour](../figures/average_speed_by_hour.png)

- [average speed by day of week](../figures/average_speed_by_day_of_week.png)

- [weekday weekend profile](../figures/weekday_weekend_profile.png)

- [morning evening congestion](../figures/morning_evening_congestion.png)

- [missingness by sensor](../figures/missingness_by_sensor.png)

- [missingness over time](../figures/missingness_over_time.png)

- [sensor variance distribution](../figures/sensor_variance_distribution.png)

- [sample sensor timeseries](../figures/sample_sensor_timeseries.png)

## Handoff and limitations

See [Person B handoff](person_b_handoff.md). Structural failures block the canonical handoff. Warning-level diagnostics require awareness, not automatic sensor deletion. `data/metadata/split_contract.json` defines timestamp boundaries only; Person B owns feature samples. No models, performance findings, graph features, SUMO or control were implemented.

## Person B handoff checks

Keep immutable raw measurements, canonical sensor order and shared split boundaries. Split the complete chronological 5-minute grid using floor70/floor10/remainder counts; all `+1/+3/+6/+12` targets of a sample must belong to one partition. Past history may use earlier observed partitions causally. Imputation and any learned statistics must use training-only fitted parameters; targets remain masked rather than imputed. Exclude neighboring sensor traffic, adjacency, coordinates and graph features from AML inputs.

Speed units and timestamp timezone remain unverified unless new source evidence establishes them. Use the same stored-clock peak definition and evaluation validity masks across the team. Read the [full handoff contract](../reports/person_b_handoff.md) before feature engineering. Person A's acceptance requires structural success, executed notebooks and reviewed outputs; the full Phase 1 additionally requires Persons B–E.